import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google"; // next/font/google에서 글꼴을 사용한다.

const inter = Inter({
  // variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
